const RESPONSE_STATUSES = {
  STATUS_OK: 200,
  STATUS_CREATED: 201,
  STATUS_BAD_REQUEST: 400,
  STATUS_UNAUTHORIZED: 401,
  STATUS_NOT_FOUND: 404,
  STATUS_SERVER_ERROR: 500,
};
module.exports = {RESPONSE_STATUSES}
